import {
  AlertTriangle,
  ArrowRight,
  Check,
  ChevronLeft,
  ChevronRight,
  Command,
  CreditCard,
  File,
  FileText,
  HelpCircle,
  Image,
  Laptop,
  Loader2,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  Settings,
  Sun,
  Trash,
  Twitter,
  User,
  X,
  Menu,
  Home,
  LayoutDashboard,
  Search,
  Bot,
  Store,
  Wallet,
  LogOut,
  ChevronDown,
  BarChart,
  Activity,
  Bell,
  Mail,
  Share2,
  Github,
} from "lucide-react";

export const Icons = {
  logo: Command,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  trash: Trash,
  post: FileText,
  page: File,
  media: Image,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: Sun,
  moon: Moon,
  laptop: Laptop,
  twitter: Twitter,
  check: Check,
  menu: Menu,
  home: Home,
  dashboard: LayoutDashboard,
  search: Search,
  bot: Bot,
  store: Store,
  wallet: Wallet,
  logout: LogOut,
  chart: BarChart,
  activity: Activity,
  bell: Bell,
  mail: Mail,
  gitHub: Github,
};
